language: python
sudo: required
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4
    - pypy3

# command to install dependencies
install:
  - pip install -q Django==1.6
  - pip install -q django-filter
  - pip install -q markdown
  - pip install -q djangorestframework
# command to run tests
script: 
  - pwd
  - python manage.py runserver
